Fix #70 adicionando /help
fga-eps-mds/2019.2-Chatbot-Nilo pull request #83
Opened 2019-11-06 17:36 UTC by ThiagoGMF

## Descrição

Com este pull request a opção /help está disponível para que o usuário possa saber os assuntos que o bot conhece

## Issues que foram resolvidas:

* Closes #70 

## Tarefas
- [x] Possuir todas as opções necessárias para o usuário.
- [x] Informar as opções de forma clara.

<p align="center">
  <img width="500" height="500" src="https://i.imgur.com/d9PJyeJ.png">
  <br />
</p>

2019-11-07 00:41 UTC, httpaiva approved these changes
A intent de risco de desligamento também usa a palavra chave "socorro". Acho que para evitar conflito, deveria remover essa palavra da intent de desligamento e deixar somente na /help. Fora esse pequeno detalhe, está aprovado.

2019-11-08 00:43 UTC, eliseukadesh67 commented
A resposta poderia ser exatamente o que o usuário pode perguntar, não necessáriamente todas as intents, mas o exemplo de cada uma. A função de dizer quais assuntos o bot sabe poderia ficar para o /start.

2019-11-08 00:44 UTC, eliseukadesh67 requested changes
A resposta poderia ser exatamente o que o usuário pode perguntar, não necessáriamente todas as intents, mas o exemplo de cada uma. A função de dizer quais assuntos o bot sabe poderia ficar para o /start.

2019-11-08 00:46 UTC, eliseukadesh67 commented
Sugestão do @gabriel-paiva :

Colocar apenas as intents mais principais para não ficar uma mensagem muito grande, e depois enviar um arquivo com todas as intents, caso o usuário queira ver todas.

2019-11-08 23:45 UTC, httpaiva approved these changes
Aprovado.

2019-11-10 20:19 UTC, merged