Fix #93 Alterando o nome da tag do build para "yukioz/requirements."
fga-eps-mds/2019.2-Chatbot-Nilo pull request #94
Opened 2019-11-19 14:11 UTC by eliseukadesh67

## Descrição

Foi realizada a alteração da tag do nome da imagem gerada ao final do treinamento do bot, que antes era "lappis/bot:boillerplate" para "yukioz/requirements".

## Resolve (Issues)
 
Corrige o seguinte Pull Request:

## Pull_Requests relacionados

branch | Pull-request
------ | ------
Fix/image_bot | #93

2019-11-19 14:13 UTC, murilogds commented
Aprovado

2019-11-19 14:13 UTC, httpaiva approved these changes
Aprovado.

2019-11-20 00:35 UTC, murilogds requested changes
A imagem que foi retirada foi a imagem do bot, não a de requirements, o certo seria trocar a imagem para yukioz/bot, não?

2019-11-20 00:57 UTC, eliseukadesh67 commented
> A imagem que foi retirada foi a imagem do bot, não a de requirements, o certo seria trocar a imagem para yukioz/bot, não?

Nome da imagem corrigida.

2019-11-20 02:07 UTC, murilogds approved these changes
Aprovado.

2019-11-21 13:38 UTC, merged